### ISSUE TITLE
[bug] sfpegCardCmp - FIeld labels not displayed correctly

### ISSUE THREAD

**Issue by ysaib** [pegros/PEG_LIST#42]
**Describe the bug**
The fields label are not displayed correctly when the user display density is set to compact. However when set to comfy, the display is okay.

**To Reproduce**
1. Load sfpegCardCmp on a lightning page
2. Click on the user icon on the top right 
3. Set display density to compact

**Expected behavior**
The fields label displayed correctly when display density is set to compact or comfy.

**Screenshots**
Compact:
![image](https://user-images.githubusercontent.com/118477150/202532138-82948fa8-4e2f-4991-8e7d-f90bd673980b.png)

Comfy:
![image](https://user-images.githubusercontent.com/118477150/202630554-512c8a75-52fc-4110-b39a-ba4386b36e79.png)

**Comment by pegros** [comment]
Problem fixed in build [a630bd1](https://github.com/pegros/PEG_LIST/commit/a630bd18461f0aadcf933f246b2c4943d8a509bf)

**Comment by pegros** [comment]
The **sfpegCardCmp** component relies on the standard **lightning-input-field** and **lightning-output-field** Lightning base components to display/edit the fields.

Unfortunately, there are no styling hooks defined on these base components to implement the same solution as for the **sfpegRecordDisplayCmp** component (i.e. add the _slds-truncate_ CSS class to the label part).

Therefore, the only option for the time being is to enforce stacked display mode at all time when there are too many fields on each row. Please specify `"density":"comfy"` in your metadata configuration.
