### ISSUE TITLE
[feat] sfpegMessageListCmp - Make visible SfpegActionBar

### ISSUE THREAD

**Issue by ismailsalam** [pegros/PEG_LIST#43]
We use the SfpegActionBar component to display action buttons related to the current record, we want to display error messages in the event that the button cannot be displayed.

SfpegMessageListCmp will meet our need well if the "sfpegactionbar" component includes in is possible to make it visible

can we have parent-context param in sfpegactionBar included in SfpegMessageListCmp

![image](https://user-images.githubusercontent.com/5978505/204484265-a5d32c2b-a740-4b9e-a5ae-d28501e970be.png)

**Comment by pegros** [comment]
Actually, after further thinking, I would rather let you implement a wrapping component including both a MessageList and an ActionBar, the hidden ActionBar included in the MessageList remaining unchanged.

**Comment by pegros** [comment]
***parent-context*** variable has been added on **sfpegListCmp**, **sfpegMessageListCmp**, **sfpegCardCmp**, **sfpegCardListCmp**, **sfpegKpiListCmp**, **sfpegProfileCmp** and **sfpegRecordDisplayCmp** in addition to **sfpegActionBarCmp**.

**Comment by pegros** [comment]
For the requested layout, teh idea would be to implement a parent component fetching and injecting a parent context in both a sfpegMessageListcmp and sfpegActionBarCmp.

**Comment by pegros** [comment]
Implemented in build [baff2ad](https://github.com/pegros/PEG_LIST/commit/baff2ad8b48bc05e2a6697ebb72108940a675de5)

**Comment by pegros** [comment]
Documentation to be updated soon...
