### ISSUE TITLE
[bug] sfpegActionBarCmp - "Disabled" flag don't work well

### ISSUE THREAD

**Issue by ismailsalam** [pegros/PEG_LIST#44]
The "disabled" flag in sfpegActionBarCmn, not work well when we modifie current record to invers the value of the flag

**Comment by pegros** [comment]
@ismailsalam I could not reproduce the issue on the latest component release ([baff2ad](https://github.com/pegros/PEG_LIST/commit/baff2ad8b48bc05e2a6697ebb72108940a675de5))

**Comment by pegros** [comment]
Issue closed. Not reproduced
