### ISSUE TITLE
[feat] sfpegProfileCmp - Support wider range of banner and avatar images

### ISSUE THREAD

**Issue by eloscarfr** [pegros/PEG_LIST#46]
**Is your feature request related to a problem? Please describe.**
Avatars (and banners) pictures are given by a Static Ressource. Even if it provides a flexibility (name of the image within the Static Ressource can be given by a custom field), it would be super useful, if a "File" can be used instead, so it could be completely dynamic (name). 
My requirement is to display the picture (name give by a custom field) of a user (custom object), without the constraint of the maximum size of static ressources (5M), and the need to update the Static Ressource image zip file, each time a new user is created (and a new avatar is needed).

**Describe the solution you'd like**
Ideally, the url to the Avatar could be given by a field of the record (formula field), linking to a File / asset. By the way, this could allow to mutualise images used on CRM-A dashboards.

**Describe alternatives you've considered**
Having the name of the static ressource given by a custom field (instead of SfpegAvatars fixed values), which will allow to get rip of the max size limitation (use of more than 1 Static ressource).

**Additional context**
n/a

**Comment by pegros** [comment]
Implemented in build [242de70](https://github.com/pegros/PEG_LIST/commit/242de70ca49d7e74c222c12875663914b1c1c8cb)

The solution relies on an additional `fileFieldName` property for avatar and banner definitions, providing the API Name of a field containing the Salesforce ID of a content document to be used.

**Comment by pegros** [comment]
Implemented in build [242de70](https://github.com/pegros/PEG_LIST/commit/242de70ca49d7e74c222c12875663914b1c1c8cb)

The solution relies on an additional `fileFieldName` property for avatar and banner definitions, providing the API Name of a field containing the Salesforce ID of a content document to be used.
It comes in addition to the previous static resource based mechanism, which may still be used as a fallback option if the `fileFieldName` value is null.

**Comment by pegros** [comment]
@eloscarfr Just added a new native option to handle standard Salesforce asset files, enabling to reference those files by their names.

**Comment by eloscarfr** [comment]
Thanks @pegros it works perfectly! 👍
