### ISSUE TITLE
[feat] sfpegCardCmp - ability to add a Custom label as a card title in experience cloud site

### ISSUE THREAD

**Issue by Mchaouche** [pegros/PEG_LIST#51]
**Is your feature request related to a problem? Please describe.**
In core, we can add a Custom label as a card title. This is not currently possible in an experience cloud site

**Describe the solution you'd like**
ability to add a Custom label as a card title

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by pegros** [comment]
@Mchaouche  In the new LWR Experience Sites, it is possible to use custom labels right in the Experience Builder by leveraging a slightly different syntax : `{!Label.c.LabelName}`.

**Comment by pegros** [comment]
Implemented in build [2928f16](https://github.com/pegros/PEG_LIST/commit/2928f1692895534c17771311e9973ff8ea02b7b9)

**Comment by pegros** [comment]
Please use `{{{LBL.LabelName}}}` merge syntax directly within the Site Builder on the `Card Title` parameter.
