### ISSUE TITLE
[bug] sfpegListCmp -  Error when the column's name defined with a custom label contains  a Single Quote 

### ISSUE THREAD

**Issue by Mchaouche** [pegros/PEG_LIST#53]
**Describe the bug**

In peglists, when we define the column's name with a custom label that contains  a Single Quote an error is thrown

**Comment by pegros** [comment]
Fixed issue in sfpegMerge_CTL component in build [c59dfed](https://github.com/pegros/PEG_LIST/commit/c59dfedc370718ef6ed3f04fbd811acf6711ae9b)
`\'` sequence in Custom Labels merged server side was generating issues in JSON parsing.
They are now replaced by standard single quotes (`'`) to prevent this.

**Comment by pegros** [comment]
FYI @jstukas
