### ISSUE TITLE
[feat] sfpegActionBarCmp - Enable usage/selection of other fields instead of Name when creating a datasource to filter a lookup field

### ISSUE THREAD

**Issue by farhaanaBalaky** [pegros/PEG_LIST#54]
**Is your feature request related to a problem? Please describe.**
When creating a datasource that is used in a LDS form in an sfpegAction , even when specifying the fieldname as PRM_CodePortefeuille__c in the display configuration, the name is being displayed as default on the LDS form.

**Describe the solution you'd like**
Display other fields than name in the lookup datasource field

Additional context
<img width="282" alt="s3" src="https://user-images.githubusercontent.com/42023201/227863411-197a26fe-c046-4562-8e71-2ab94f21c5ee.png">
<img width="381" alt="s2" src="https://user-images.githubusercontent.com/42023201/227863419-8534a818-d7b0-47ff-bfc6-8f0953896b78.png">
<img width="514" alt="s1" src="https://user-images.githubusercontent.com/42023201/227863425-bcb60e21-c054-4acb-9e09-4dd3ed86cd7c.png">

**Comment by pegros** [comment]
There is already a `labelField` available in the `sfpegPicklistInputDsp` component to achieve this but passing a config value for it is not implemented in the `sfpegPopupDsp` parent component used to display the creation/edit popup.
I shall add a new configuration parameter ASAP and propagate it down to the picklist input component.

**Comment by pegros** [comment]
Feature implemented with commit  [b7986d9](https://github.com/pegros/PEG_LIST/commit/b7986d926cac9890d63bc577fff15b68d628227c)

Just add a `dataLabel` property in addition to the `dataSource` to specify a different label field.

**Comment by pegros** [comment]
FYI @jstukas
