### ISSUE TITLE
[feat] sfpegActionBarCmp - Habilité de charger des fichiers excel/csv

### ISSUE THREAD

**Issue by VeekeshPie** [pegros/PEG_LIST#55]
Bonjour,

Est-ce qu'on a la possibilité de charger des fichiers excel/ csv sur le bouton d'action du type upload car on reçois un message d'erreur à la chargement d'un fichier excel comme vue dans le pj ci dessous.

![image](https://github.com/pegros/PEG_LIST/assets/89961284/75ae8491-dd8f-46ef-af29-c6ae3890fe7b)

Et voici le config qu'on a mis en place sur PRM:

	    [
            {
            "name": "file",
            "label": "Charger des fichiers",
            "iconName": "utility:upload",
            "action": {
            "type": "upload",
            "params": {
            "title": "Charger des fichiers",
            "label": "Plusieurs fichiers possibles",
            "recordId": "{{{GEN.recordId}}}",
            "formats": [
            ".pdf",
            ".jpg",
            ".jpeg"
            ],
            "allowMultiple": true,
            "next": {
            "type": "notify",
            "channel": "RefreshList",
            "params": {
            "type": "done",
            "params": {
            "type": "refresh"
            }
            }
            }
            }
            }
            }
            ]
            
 Merci par avance pour ton aide.

**Comment by pegros** [comment]
@VeekeshPie  It is possible by simply overriding the `formats` property in your configuration.
