### ISSUE TITLE
[bug] sfpegCardCmp - Google Map & Address Bar not displaying for field type Address

### ISSUE THREAD

**Issue by Bousun** [pegros/PEG_LIST#56]
Bonjour @pegros,

J'ai reçu une demande dans laquelle je dois utiliser le composant sfpegCardCmp pour afficher l'adresse postale (Data type = Address, API Name= BillingAddress) d'un compte, ainsi que sa **carte** google. 

Exemple : 
![image](https://github.com/pegros/PEG_LIST/assets/73889173/cb23fec7-c252-45b6-b543-bebcd7d41e16)
Cela a été fait via le composant standard de Salesforce Record Detail.

Cependant, lorsque j'utilise le composant sfpegCardCmp avec la configuration suivante :

{
   "size":6,
   "fields":[
      {
         "name":"BillingAddress"
      }
   ]
}

Seule l'adresse est affichée et non la carte Google. Exemple : 
![image](https://github.com/pegros/PEG_LIST/assets/73889173/2a307f52-4154-463e-afcc-782ed69fbda7)

De plus, lorsqu'on modifie l'adresse, une barre de recherche s'affiche normalement, comme indiqué ci-dessous.

![image](https://github.com/pegros/PEG_LIST/assets/73889173/b8ce2c6c-6540-4c8d-84ae-5f65a0cac04e)

Cette barre ne s'affiche pas non plus lorsque j'utilise sfpegCardCmp.

Merci d'avance pour ton précieux retour d'information.

Cdt, 
Bousun

**Comment by pegros** [comment]
@Bousun
The **sfpegCardCmp** component relies on the Salesforce standard **lightning-record-edit-form** and **lightning-input-field** base components. The issues you are describing are limitations of these base components for address fields.
I do not plan to fix such issues in this package.
You should perhaps give a try to ask the community to fix the **lightning-input-field** from the opensource project. See https://www.npmjs.com/package/lightning-base-components

**Comment by Bousun** [comment]
@pegros 

Okay, it's noted. 

Thank you very much.

Regards.
