### ISSUE TITLE
[feat] sfpegListCmp - Récupérer une liste d'IDs provenant de rangées sélectionnées sous un Header Action pour effectuer une action

### ISSUE THREAD

**Issue by irfan2102** [pegros/PEG_LIST#57]
Hello @pegros 

Je ne peux pas faire une action custom qui appelle un flux en passant la liste des Ids pour les rangées sélectionnées en masse.

C'est possible de faire évoluer le composant pour qu'on puisse r'écupérer les IDs des donné sélecté en masse afin qu'on puisse faire des action. Ex: passer les ID sélectionner dans un flow lorsque je clique sur un header action dans la PEG LIST?

                       "flowparams" : [
                           {
                              "name" : "lwcInput",
                              "type"  : "String",
                              "value" : "selectedRows.AccountId"
                           }
                       ]
![Untitled (5)](https://github.com/pegros/PEG_LIST/assets/78501565/d0024061-bf78-47a9-9be7-fac461524e47)

**Comment by pegros** [comment]
@irfan2102
This should be feasible but I might need some time to let it work properly.
I indeed would need to review the way flows are launched in popups (to leverage the LWC lightning-flow instead of legacy Aura), how a list of items may be properly passed as input (I only tested with unitary values) and enhance the sfpegMergeUtl to generate such a list.

**Comment by pegros** [comment]
@irfan2102 Just implemented a first solution on the current Aura basis.
Please have a look at https://github.com/pegros/PEG_LIST/blob/master/help/sfpegActionUtilityCmp.md#openflow-action-type-for-mass-operations.
Beware that, even if most impacts are on the **sfpegActionUtilityCmp** components, other ones are also impacted.
Please let me know if you encounter any issue.
