### ISSUE TITLE
[feat] sfpegCardCmp - Support hidden fields

### ISSUE THREAD

**Issue by ismailsalam** [pegros/PEG_LIST#58]
Hello,

_**Request for desired development:**_
Add the possibility in the SFPEGCard component to manage hidden fields. For example, manage dependent selection lists whose dependent field should not be displayed

**_Details of the desired development:_**
Add the ability to handle a "class" attribute in the display fields definition to inject an SLDS-style class

**_Example of expected evolution:_** 
> Custom metadata "sfpegCard"
> "Display Configuration" field:
{  
   "size": 6,
   "fields": [
    {      
      "name": "Suivi__c" 
    },
    {
      "name": "canal__c",
      **"class": "slds-hide"**  
    }
  ]
}

**Comment by pegros** [comment]
Feature added in the component via a `context` global property similar to `fields` instead of a field definition level one.
Context fields are loaded only when switching to edit mode.
