### ISSUE TITLE
[bug] sfPegProfileCmp - Soucis d'affichage du chargé de clientèle sur les Sandbox en preview Winter 24

### ISSUE THREAD

**Issue by vjallim** [pegros/PEG_LIST#59]
Bonjour @pegros,

Nous avons rencontré un souci sur l'affichage du chargé de clientèle (Account.OwnerId) sur les Sandbox en preview Winter 24.  
Le chargé de clientèle ne s'affiche pas sur le composant sfPegProfileCmp LWC. 

Sur notre analyse, le composant utilise en back-end est le **lightning-output-field** de Salesforce pour afficher les champs configurés sur le custom metadata sfPegProfile.

sfPegProfileCmp UI: 
![image](https://github.com/pegros/PEG_LIST/assets/53938812/37ed4aa8-10c5-4e27-b484-36e39f00b8db)

Custom Metadata:
![image](https://github.com/pegros/PEG_LIST/assets/53938812/c84c4e11-8b09-42f6-aff0-be39016a47f0)

Documentation du composant lightning-output-field:
[ https://developer.salesforce.com/docs/component-library/bundle/lightning-output-field/documentation](https://developer.salesforce.com/docs/component-library/bundle/lightning-output-field/documentation)

Pour l'instant, la solution de contournement préférable est d'utiliser un champ formule avec un hyperlien qui réplique le même comportement de celui du champ standard:
![image](https://github.com/pegros/PEG_LIST/assets/53938812/85d36e73-039d-413f-978d-8e6019f3c300)

Est-ce que vous avez plus d'info sur le souci d'affichage du chargé de clientèle (Account.OwnerID) sur les Sandbox en preview Winter 24?

Cordialement,
Vyas

**Comment by pegros** [comment]
Closed.... not reproduced recently.
