### ISSUE TITLE
[bug] SFPEGRecordListDisplay- Flow: The componenent shows 'null' values

### ISSUE THREAD

**Issue by Mchaouche** [pegros/PEG_LIST#60]
**Describe the bug**
in SFPEG Record List Display component, when a field is not filled a null value is shown (cf; Image)

**Expected behavior**
Nothing is shown

**Screenshots**
![image](https://github.com/pegros/PEG_LIST/assets/14328205/347e6818-11a7-481e-a821-92f83658348e)

**Comment by pegros** [comment]
@Mchaouche I shall have a look at this ASAP.

**Comment by pegros** [comment]
@Mchaouche Just had a look at your issue and cannot reproduce it.
Could you provide additional details ?
By the way, you opened the issue on the wrong repository (PEG_LIST instead of PEG_FLW)

**Comment by pegros** [comment]
<img width="979" alt="Capture d’écran 2023-10-23 à 08 58 16" src="https://github.com/pegros/PEG_LIST/assets/27245946/f4b0a605-e0a4-466e-9de5-a8a799fd992c">

**Comment by pegros** [comment]
Closed issue... not reproduced
