### ISSUE TITLE
[feat] sfpegCard - Display Record on an Lightning App Page

### ISSUE THREAD

**Issue by Daphne971** [pegros/PEG_LIST#62]
**Is your feature request related to a problem? Please describe.**
I would like to display some record content into an App Page. Unfortunately the sfpegCard component is not available for an App Page.

**Describe the solution you'd like**
I'd like to be able for the sfpegCard  to be able to pass the Id of a record using sfpegMerge and display the data I want on an App Page.

**Describe alternatives you've considered**
X

**Additional context**
The idea here is to be able to display a Knowledge article via sfpegCard on an App Page

**Comment by pegros** [comment]
Thanks @Daphne971  I shall have a look at this ASAP.

**Comment by pegros** [comment]
Implemented in commit [c2b9c35](https://github.com/pegros/PEG_LIST/commit/c2b9c356137f4c5b710e3db4addc9b92839425d1)
One new **sfpegAppCardCmp** component added as a wrapper component example.
