### ISSUE TITLE
[bug] sfpegListCmlp - CSV export on tree grid does not work

### ISSUE THREAD

**Issue by AleFSalesforce** [pegros/PEG_LIST#64]
**Describe the bug**
While having a sfpegListCmp configure as tree grid, when configure the action for export, file is generated empty.

**To Reproduce**
1. Add a sfpegListCmp to a record page
2. Configure the list as tree grid
3. Configure a header action for file export
4. File is generated and downloaded is empty

**Expected behavior**
File generated (and downloaded) with the content shown on screen.

**Screenshots**
<img width="1302" alt="image (10)" src="https://github.com/pegros/PEG_LIST/assets/91567590/f036489d-840d-4c75-b1e4-7d6f0e8ea5cc">

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: Chrome

**Smartphone (please complete the following information):**
Not tested

**Additional context**
N/A.

**Comment by pegros** [comment]
Just renamed your issue @AleFSalesforce and shall give it a look asap.

**Comment by pegros** [comment]
@AleFSalesforce Just discovered that the issue was larger than expected (i.e. for standard lists also). I am starting to look at it for my current customer and shall keep you posted.

**Comment by pegros** [comment]
@AleFSalesforce Problem fixed and DataTree export now properly supported (recursive children export + addition of row and parent key columns)
