### ISSUE TITLE
[bug] SfPegActionBar - Data record value breaks JSON format

### ISSUE THREAD

**Issue by ismailsalam** [pegros/PEG_LIST#65]
**Describe the bug**
When we try to merge variable which contains a specific charachter double quotation ", its breakes the format JSON of file configName, then the component fail and don't display the bottons. 
We think this is true for all others Peg components

**To Reproduce**
1. Go to a custom metadataType of sfpegActionBar
2. use variable like {{{RCD.Name}}}
3. if the value of RCD.Name contains a double quotation charachter like 'ADM" Paris'
4. the component Fail, and don't display the bottons  

**Expected behavior**
List of bottons displayed --> at the merging of data, we need to escape the double quote.

**Comment by pegros** [comment]
@ismailsalam Did you have the chance to test my recommendation ? Is this still a valid bug ?

**Comment by pegros** [comment]
No change done.

**Comment by ismailsalam** [comment]
Sorry for the late response, yes I tested your recommendation, and it works fine. THANKS
