### ISSUE TITLE
[bug] sfpeg-list-cmp - Regression UI from spring release 

### ISSUE THREAD

**Issue by alexispissinier** [pegros/PEG_LIST#66]
**Describe the bug**
Since spring release we observed different size button in the sfpeg list header actions, particularly with drop down list button.

**To Reproduce**
1. Configure a sfpeg list component on a lightning page with sorting capabilities for example
2. Go to the lightning page and observe the issue

**Investigations**
After talking with Salesforce support, here is the final conclusion:
Root Cause Analysis of the issue :-
As mentioned previously this is occurring because of the component size properties, the size is affected due to the LWC component rendering on the property called "border-filled".
There is no offical proof that the css behind changed with the release..

So we detect in the following components the variant="border-filled" used
c-sfpeg-action-bar-cmp
c-sfpeg-list-cmp

**Screenshots of the issue**
![image](https://github.com/pegros/PEG_LIST/assets/16622515/c9a15453-cffb-432c-9c61-a4d73721fb33)
![image](https://github.com/pegros/PEG_LIST/assets/16622515/72fc68d0-f688-4016-96a8-d8773be78fb4)

**Comment by pegros** [comment]
@alexispissinier Issue fixed ! Thanks for the hint.
