### ISSUE TITLE
[feat] sfpegList - Execute queries on display

### ISSUE THREAD

**Issue by xdefos** [pegros/PEG_LIST#68]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm using the List component and I'd like it not to execute SOQL queries on display. I'd like this to be done on user click.
In fact, I have a page that already has a large ETP and I don't want to make it any heavier. Do you have any configuration ideas to address this need?

**Describe alternatives you've considered**
One option would be to have conditional display on a Boolean field on the record or the user to display the list vs a field change action button.

**Additional context**
In my use case, I'm using a List with an Apex CTL to fetch and merge SOQL queries in Custom Object and External Object

**Comment by pegros** [comment]
@xdefos I shall have a look at this asap.

**Comment by pegros** [comment]
![Capture d’écran 2024-04-24 à 14 13 25](https://github.com/pegros/PEG_LIST/assets/27245946/d25250b5-360f-454e-add3-6c23063aee22)
![Capture d’écran 2024-04-24 à 14 13 40](https://github.com/pegros/PEG_LIST/assets/27245946/ae54e202-5fbb-440b-9a18-59197e2bd968)
![Capture d’écran 2024-04-24 à 14 13 52](https://github.com/pegros/PEG_LIST/assets/27245946/34d23dd0-5840-4791-be00-19d77dbcefa6)

**Comment by pegros** [comment]
@xdefos I shall close this issue as I provided a solution meeting your requirements (even though not directly on the **sfpegListCmp** component).
