### ISSUE TITLE
[feat] sfpegListCmp - Increase length for QueryOrderBy__c in sfpegList__mdt

### ISSUE THREAD

**Issue by AleFSalesforce** [pegros/PEG_LIST#72]
**Is your feature request related to a problem? Please describe.**
Custom fields API Name in projects where I've been working often have a length larger than 25 characters, which is the current length for QueryOrderBy__c in sfpegList__mdt.

**Describe the solution you'd like**
Increase the length for QueryOrderBy__c in sfpegList__mdt. Suggestion: minimum 50. I've already change it in my org.

**Describe alternatives you've considered**
Change custom fields API Name to value shorter than 25. Issue here is that fields might be already in used (in may case, is used by a third party via API), so making this change has higher cost.

**Additional context**
-

**Comment by pegros** [comment]
@AleFSalesforce 
Shall do it ASAP

**Comment by pegros** [comment]
@AleFSalesforce done !
